name: ManualDeploy
concurrency: "${{ github.event.inputs.aws_environment }}"

on:
  workflow_dispatch:
    inputs:
      aws_environment:
        description: 'AWS environment'
        required: true
        default: 'scratch0'
jobs:
  deploy:
    # NOTE: this is unsafe.
    # github-actions allows for ANYONE with push new branch privs to update
    # the workflow files and run a build using their customized workflow from
    # their own branch.
    # DO NOT EVER GIVE GITHUB-ACTIONS ACCESS TO A PRODUCTION ENV
    if: ( github.ref == 'refs/heads/master' && contains(fromJson('["scratch0", "scratch1", "dev1", "qa1", "prod1"]'), github.event.inputs.aws_environment))
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install -g serverless

    - name: Deploy Lambdas
      env:
        AWS_ACCOUNT_KEYS: ${{ secrets.AWS_ACCOUNT_KEYS }}
      run: |
        # retrieve the creds from the env
        export AWS_ACCESS_KEY_ID=`echo $AWS_ACCOUNT_KEYS | base64 -d | grep "${{ github.event.inputs.aws_environment }}" | cut -f2 -d ":"`
        export AWS_SECRET_ACCESS_KEY=`echo $AWS_ACCOUNT_KEYS | base64 -d | grep "${{ github.event.inputs.aws_environment }}" | cut -f3 -d ":"`

        serverless deploy

